# Generated by Django 3.0.3 on 2020-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedorder',
            name='choice_cuts',
            field=models.ManyToManyField(to='deer_wait_list.MeatCut'),
        ),
    ]
