# Generated by Django 3.0.3 on 2020-09-08 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0003_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedorder',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavor', to='deer_wait_list.Flavor'),
        ),
    ]
