# Generated by Django 3.0.7 on 2020-10-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0004_requestedorder_flavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestedorder',
            options={'ordering': ('order_date', '-pk')},
        ),
        migrations.RenameField(
            model_name='requestedorder',
            old_name='removal_date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='requestedorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
