# Generated by Django 3.0.7 on 2020-10-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0005_auto_20201017_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedorder',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='requestedorder',
            name='order_complete',
            field=models.BooleanField(default=False),
        ),
    ]
