# Generated by Django 3.0.7 on 2020-10-18 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0006_auto_20201017_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestedorder',
            options={'ordering': ('order_complete', '-order_date', '-pk')},
        ),
        migrations.AlterField(
            model_name='recipient',
            name='perceived_thankfulness',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
