# Generated by Django 3.0.7 on 2020-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0007_auto_20201017_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
