# Generated by Django 3.0.7 on 2021-04-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deer_wait_list', '0008_requestedorder_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('name',), 'permissions': (('view_thankfulness', 'View Thankfulness'),)},
        ),
    ]
