# Generated by Django 3.0.7 on 2020-10-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('file_name', models.ImageField(blank=True, null=True, upload_to='uploads/content_collection/videos/')),
            ],
            options={
                'ordering': ('file_title', 'file_name'),
            },
        ),
    ]
