# Generated by Django 3.0.7 on 2020-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-pk', 'restricted', 'file_title', 'file_name')},
        ),
        migrations.AddField(
            model_name='video',
            name='restricted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='uploads/content_collection/videos/'),
        ),
    ]
