# Generated by Django 3.0.7 on 2020-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0003_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ('caption', '-pk')},
        ),
        migrations.AddField(
            model_name='carousel',
            name='caption',
            field=models.CharField(blank='no name yet', max_length=250, null=True),
        ),
    ]
