# Generated by Django 3.0.7 on 2020-10-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0004_auto_20201017_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='PicturesForCarousel',
        ),
    ]
