# Generated by Django 3.0.7 on 2020-10-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0008_auto_20201017_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesforcarousel',
            name='required_group_to_view',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
