# Generated by Django 3.0.7 on 2020-10-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0009_picturesforcarousel_required_group_to_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picturesforcarousel',
            options={'ordering': ('-pk', 'caption')},
        ),
        migrations.RemoveField(
            model_name='picturesforcarousel',
            name='required_group_to_view',
        ),
    ]
