# Generated by Django 3.0.7 on 2020-10-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0011_picturesforcarousel_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DandDFifthEditionBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='uploads/content_collection/dnd5e_books/')),
                ('restricted', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ('-pk', 'restricted', 'file_title', 'file_name'),
            },
        ),
    ]
