# Generated by Django 3.0.7 on 2020-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0012_danddfiftheditionbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyGrounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='uploads/content_collection/FantasyGrounds/')),
            ],
            options={
                'ordering': ('-pk', 'file_title', 'file_name'),
            },
        ),
    ]
