# Generated by Django 3.0.7 on 2020-12-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0014_auto_20201211_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danddfiftheditionbook',
            options={'ordering': ('-pk', 'file_title', 'file_name'), 'verbose_name': 'D & D 5th Edition Book', 'verbose_name_plural': 'D & D 5th Edition Book'},
        ),
        migrations.AlterModelOptions(
            name='fantasygrounds',
            options={'ordering': ('-pk', 'file_title', 'file_name'), 'verbose_name': 'Fantasy Grounds', 'verbose_name_plural': 'Fantasy Grounds'},
        ),
        migrations.AlterModelOptions(
            name='picturesforcarousel',
            options={'ordering': ('-pk', 'caption'), 'verbose_name': 'Picture For Carousel', 'verbose_name_plural': 'Pictures For Carousel'},
        ),
    ]
