# Generated by Django 3.0.7 on 2021-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0015_auto_20201211_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='danddfiftheditionbook',
            name='restricted',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
