# Generated by Django 3.0.7 on 2021-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0016_danddfiftheditionbook_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomInsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Random Insult',
                'verbose_name_plural': 'Random Insults',
                'ordering': ('-pk', 'file_title'),
            },
        ),
    ]
