# Generated by Django 3.0.7 on 2021-03-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0018_auto_20210320_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randominsult',
            name='insult',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
