# Generated by Django 3.0.7 on 2021-04-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0019_auto_20210320_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
                'ordering': ('-pk',),
            },
        ),
    ]
