# Generated by Django 3.0.7 on 2021-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0021_buzzwordorphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzzwordorphrase',
            name='word_or_phrase',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
