# Generated by Django 3.0.7 on 2021-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0023_sensorreadings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoUnoSketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch_datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('intent', models.TextField(blank=True, null=True)),
                ('sketch', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sketch',
                'verbose_name_plural': 'Sketches',
                'ordering': ('-sketch_datetime',),
            },
        ),
    ]
