# Generated by Django 3.0.7 on 2021-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_collection', '0025_auto_20210429_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinounosketch',
            name='restricted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
