# Generated by Django 3.0.7 on 2020-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_watcher', '0002_auto_20200913_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchitem',
            name='item_phrase',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
