# Generated by Django 3.0.7 on 2020-09-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_watcher', '0003_auto_20200913_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchitem',
            name='item_phrase_not_exist',
        ),
    ]
