# Generated by Django 3.0.7 on 2020-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_watcher', '0004_remove_watchitem_item_phrase_not_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='item_phrase_not_exist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
