# Generated by Django 3.0.7 on 2020-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_watcher', '0005_watchitem_item_phrase_not_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='item_exception',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
