# Generated by Django 3.0.7 on 2020-09-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_watcher', '0006_watchitem_item_exception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchitem',
            options={'ordering': ('-item_phrase_not_exist', 'item_name')},
        ),
    ]
