version: '3'

services:
  unicorn_web:
    hostname: unicorn_web
    image: benspelledabc/django-imrunicorn:2.4
    depends_on:
      - unicorn_db
      - adminer
    ports:
        - "80:8020"
    volumes:
        - ./data/:/opt/app/imrunicorn/data/
        - ./uploads/:/opt/app/imrunicorn/media/uploads/
        - ./certs/:/opt/app/certs/

  unicorn_db:
    # image: mysql:5.7
    image: mariadb
    hostname: unicorn_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imrunicorn
      MYSQL_DATABASE: imrunicorn
      MYSQL_USER: imrunicorn
      MYSQL_PASSWORD: imrunicorn

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_data:
