version: '3'

services:
  unicorn_web:
    hostname: unicorn_web
    image: benspelledabc/djangosite:3.14.51
    restart: always
    depends_on:
      - unicorn_db
      - adminer
    ports:
        - "80:8020"
        - "443:443"
    volumes:
        - ./data/:/opt/app/imrunicorn/data/
        - ./uploads/:/opt/app/imrunicorn/media/uploads/
        - ./certs/:/opt/app/certs/
        # i use this volume for version control, sure there are better/easier ways
        # - /data/django/imrunicorn/release.json:/opt/app/imrunicorn/release.json
        # - ${PWD}/release.json:/opt/app/imrunicorn/release.json


  unicorn_db:
    image: mariadb
    hostname: unicorn_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imrunicorn
      MYSQL_DATABASE: imrunicorn
      MYSQL_USER: imrunicorn
      MYSQL_PASSWORD: imrunicorn

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_data:
