-
    name: Install Web Services
    hosts: endservers
    tasks:
        - name: Install httpd service
          yum:
              name: httpd
              state: present

        - name: Start web server
          service:
              name: httpd
              state: started

        - name: install the latest version of git
          yum:
            name: git
            state: latest


        - git:
            repo: 'https://github.com/username/IMRUnicornDjango.git'
            dest: /data/zomg-git
            version: v3.142

