# Generated by Django 3.0.3 on 2020-08-21 03:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(default='Mixed', max_length=150)),
                ('brass_on_hand', models.IntegerField(default=100, null=True)),
                ('buy_link', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('author_pk', models.IntegerField(default=1, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('caliber', 'manufacture'),
            },
        ),
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=5)),
                ('author_pk', models.IntegerField(default=1, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('barrel_length', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, null=True)),
                ('inches_per_twist', models.DecimalField(decimal_places=1, default=9.0, max_digits=4, null=True)),
                ('clicks_from_bottom_to_zero_elevation', models.IntegerField(blank=True, default=-1)),
                ('clicks_from_bottom_to_zero_windage', models.IntegerField(blank=True, default=-1)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('caliber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Caliber', to='loaddata.Caliber')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'caliber', 'manufacture', 'model'),
            },
        ),
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_smokeless', models.BooleanField(default=True)),
                ('buy_link', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('lbs_on_hand', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, null=True)),
                ('author_pk', models.IntegerField(default=1, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'is_smokeless'),
            },
        ),
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(default='Mixed', max_length=150)),
                ('description', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('units_on_hand', models.IntegerField(default=100, null=True)),
                ('buy_link', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('author_pk', models.IntegerField(default=1, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('manufacture', 'description'),
            },
        ),
        migrations.CreateModel(
            name='Projectile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('WeightGR', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Diameter', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Ballistic_Coefficient', models.DecimalField(decimal_places=4, default=0.24, max_digits=5)),
                ('projectiles_on_hand', models.IntegerField(default=100, null=True)),
                ('buy_link', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('author_pk', models.IntegerField(default=1, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('WeightGR', 'Manufacture'),
            },
        ),
        migrations.CreateModel(
            name='HandLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Powder_Charge', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Velocity', models.IntegerField(default=1200, null=True)),
                ('Is_Sheriff_Load', models.BooleanField(default=True)),
                ('brass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brass', to='loaddata.Brass')),
                ('firearm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firearm', to='loaddata.Firearm')),
                ('powder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaddata.Powder')),
                ('primer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primer', to='loaddata.Primer')),
                ('projectile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='loaddata.Projectile')),
            ],
            options={
                'ordering': ('firearm', '-projectile', '-Velocity'),
            },
        ),
        migrations.CreateModel(
            name='EstimatedDope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moa_100', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_125', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_150', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_175', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_200', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_225', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_250', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_275', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_300', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_325', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_350', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_375', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_400', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_425', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_450', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_475', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_500', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_525', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_550', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_575', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_600', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_625', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_650', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_675', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_700', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_725', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_750', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_775', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_800', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_825', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_850', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_875', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_900', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_925', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_950', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_975', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_1000', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_1025', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_1050', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('moa_1075', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('hand_load', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaddata.HandLoad')),
            ],
        ),
        migrations.AddField(
            model_name='brass',
            name='caliber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caliber', to='loaddata.Caliber'),
        ),
    ]
