# Generated by Django 3.0.2 on 2020-01-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_smokeless', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'is_smokeless'),
            },
        ),
        migrations.CreateModel(
            name='Projectile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('WeightGR', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Diameter', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Ballistic_Coefficient', models.DecimalField(decimal_places=4, default=0.24, max_digits=5)),
            ],
            options={
                'ordering': ('WeightGR', 'Manufacture'),
            },
        ),
        migrations.CreateModel(
            name='HandLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Powder_Charge', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Chamber', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Velocity', models.IntegerField(default=1200, null=True)),
                ('Barrel_Length', models.DecimalField(decimal_places=1, default=18.0, max_digits=5, null=True)),
                ('Is_Shamus_OCW', models.BooleanField(default=True)),
                ('Is_Sven_OCW', models.BooleanField(default=True)),
                ('Is_Sheriff_Load', models.BooleanField(default=True)),
                ('powder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaddata.Powder')),
                ('projectile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='loaddata.Projectile')),
            ],
            options={
                'ordering': ('Chamber', '-projectile', '-Velocity'),
            },
        ),
    ]
