# Generated by Django 3.0.3 on 2020-08-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handload',
            name='Extreme_Spread',
            field=models.IntegerField(default=1200, null=True),
        ),
        migrations.AddField(
            model_name='handload',
            name='Is_Estimated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='handload',
            name='Standard_Deviation',
            field=models.IntegerField(default=1200, null=True),
        ),
    ]
