# Generated by Django 3.0.3 on 2020-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handload',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
