# Generated by Django 3.0.3 on 2020-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0002_auto_20200820_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='handload',
            name='Confirmed_Splat_Factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handload',
            name='Group_Size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='handload',
            name='Extreme_Spread',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handload',
            name='Standard_Deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handload',
            name='Velocity',
            field=models.IntegerField(default=2200, null=True),
        ),
    ]
