# Generated by Django 3.0.7 on 2020-12-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0004_handload_coal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handload',
            options={'ordering': ('firearm__owner', 'projectile__Diameter', '-Velocity')},
        ),
    ]
