# Generated by Django 3.0.7 on 2021-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0004_handload_coal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handload',
            options={'ordering': ('-projectile__Diameter', '-projectile__WeightGR', '-Velocity')},
        ),
        migrations.AlterModelOptions(
            name='projectile',
            options={'ordering': ('-Diameter', '-WeightGR')},
        ),
        migrations.AlterField(
            model_name='projectile',
            name='WeightGR',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
