# Generated by Django 3.0.7 on 2021-03-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0005_auto_20210312_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brass',
            options={'ordering': ('-caliber__diameter', 'caliber__name', 'manufacture'), 'verbose_name': 'Brass', 'verbose_name_plural': 'Brass'},
        ),
        migrations.AlterModelOptions(
            name='caliber',
            options={'ordering': ('diameter', 'name')},
        ),
        migrations.AlterModelOptions(
            name='firearm',
            options={'ordering': ('-caliber__diameter', 'owner', 'manufacture', 'model')},
        ),
    ]
