# Generated by Django 3.0.3 on 2020-08-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='removalsbylocation',
            name='kill_shot_three',
        ),
    ]
