# Generated by Django 3.0.7 on 2020-12-30 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0002_remove_removalsbylocation_kill_shot_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalsbylocation',
            name='estimated_temperature',
            field=models.IntegerField(default=75, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(-50)]),
        ),
    ]
