# Generated by Django 3.0.7 on 2020-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0003_removalsbylocation_estimated_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalsbylocation',
            name='cloud_level',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy')], default='Sunny', max_length=20),
        ),
    ]
