# Generated by Django 3.0.7 on 2020-12-31 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0004_removalsbylocation_cloud_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalsbylocation',
            name='cloud_level',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='removalsbylocation',
            name='estimated_temperature',
            field=models.IntegerField(default=-49, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(-50)]),
        ),
    ]
