# Generated by Django 3.0.7 on 2021-01-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0006_auto_20210105_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalsbylocation',
            name='wind_dir',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='removalsbylocation',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
