# Generated by Django 3.0.7 on 2021-01-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0007_auto_20210105_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='removalsbylocation',
            options={'ordering': ('-removal_date', 'shooter__userprofile__preferred_display_name', 'shot_distance_yards')},
        ),
    ]
