# Generated by Django 3.0.7 on 2021-02-22 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0010_auto_20210131_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_shot', models.ImageField(blank=True, null=True, upload_to='uploads/groundhog_kill_shots/')),
                ('photo_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='removalsbylocation',
            name='removal_photos',
            field=models.ManyToManyField(null=True, to='groundhog_logbook.RemovalPhoto'),
        ),
    ]
