# Generated by Django 3.0.7 on 2021-02-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0013_auto_20210222_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='removalphoto',
            options={'ordering': ('-photo_date', '-id')},
        ),
    ]
