# Generated by Django 3.0.7 on 2021-02-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0014_auto_20210222_1856'),
        ('groundhog_logbook', '0014_auto_20210222_2031'),
    ]

    operations = [
    ]
