# Generated by Django 3.0.7 on 2021-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0015_merge_20210223_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalsbylocation',
            name='foot_hold_trapped',
            field=models.BooleanField(default=False),
        ),
    ]
