# Generated by Django 3.0.7 on 2021-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0017_removalsbylocation_yards_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalsbylocation',
            name='wind_dir',
            field=models.IntegerField(default=-1),
        ),
    ]
