# Generated by Django 3.0.7 on 2021-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0019_removalsbylocation_wind_dir_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalsbylocation',
            name='icon',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
