# Generated by Django 3.0.7 on 2021-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundhog_logbook', '0020_removalsbylocation_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removalsbylocation',
            old_name='icon',
            new_name='weather_icon_url',
        ),
    ]
