# Generated by Django 3.0.7 on 2021-02-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityphotovalidation',
            name='activity_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_log.ActivityLog'),
        ),
    ]
