# Generated by Django 3.0.7 on 2021-02-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0005_activity_sfw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityphotovalidation',
            options={'ordering': ('-activity_log', 'id'), 'verbose_name': 'Activity Photo Validation', 'verbose_name_plural': 'Activity Photo Validations'},
        ),
    ]
