# Generated by Django 3.0.7 on 2021-02-18 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0006_auto_20210218_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='transaction_amount',
            field=models.IntegerField(default=-2, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-100)]),
        ),
    ]
