# Generated by Django 3.0.7 on 2021-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0007_auto_20210218_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
