# Generated by Django 3.0.7 on 2021-04-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_format', models.CharField(choices=[('Email', 'Email'), ('Snail Mail', 'Snail Mail'), ('Other', 'Other')], default='Email', max_length=20)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('requester_alias', models.CharField(max_length=50)),
                ('ticket_number_received', models.DateField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=150, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('received_pa_info_requested', models.BooleanField(default=False)),
                ('request_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('request_date', '-requester_alias'),
            },
        ),
    ]
