# Generated by Django 3.0.7 on 2021-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcsa_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttimeline',
            options={'ordering': ('-request_date', '-pk', 'requester_alias')},
        ),
    ]
