# Generated by Django 3.0.7 on 2021-04-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcsa_info', '0002_auto_20210402_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttimeline',
            options={'ordering': ('-request_date', '-pk', 'requester_alias'), 'permissions': [('ticket_number_viewer', 'Can view ticket numbers')]},
        ),
    ]
