# Generated by Django 3.0.7 on 2021-04-25 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerHubWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pusher', models.CharField(max_length=450)),
                ('repo_name', models.CharField(max_length=450)),
                ('tag', models.CharField(max_length=450)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('-date_created', '-tag'),
            },
        ),
    ]
