# Generated by Django 3.0.7 on 2021-04-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockerhubwebhook',
            options={'ordering': ('-date_created', '-tag'), 'verbose_name': 'Docker Hub Webhook', 'verbose_name_plural': 'Docker Hub Webhooks'},
        ),
    ]
