# Generated by Django 3.0.7 on 2021-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeachedMemePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leached Meme Preview',
                'verbose_name_plural': 'Leached Meme Previews',
                'ordering': ('post_link',),
            },
        ),
        migrations.CreateModel(
            name='LeachedMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.CharField(max_length=250)),
                ('subredit', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250, unique=True)),
                ('nsfw', models.BooleanField(default=False, null=True)),
                ('spoiler', models.BooleanField(default=False, null=True)),
                ('author', models.CharField(max_length=150)),
                ('ups', models.IntegerField(default=1, null=True)),
                ('preview', models.ManyToManyField(blank=True, to='meme_leach.LeachedMemePreview')),
            ],
            options={
                'verbose_name': 'Leached Meme',
                'verbose_name_plural': 'Leached Memes',
                'ordering': ('subredit',),
            },
        ),
    ]
