# Generated by Django 3.0.7 on 2021-04-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_leach', '0003_leachedmeme_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leachedmeme',
            options={'ordering': ('subreddit',), 'verbose_name': 'Leached Meme', 'verbose_name_plural': 'Leached Memes'},
        ),
        migrations.RenameField(
            model_name='leachedmeme',
            old_name='subredit',
            new_name='subreddit',
        ),
    ]
