# Generated by Django 3.0.7 on 2021-04-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_leach', '0004_auto_20210430_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leachedmeme',
            name='preview',
        ),
    ]
