# Generated by Django 3.0.3 on 2020-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='reference_link',
            field=models.CharField(blank=True, default=None, max_length=450, null=True),
        ),
    ]
