# Generated by Django 3.0.3 on 2020-08-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvests',
            name='bonus_for_not_unpleasant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='harvests',
            name='harvest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='harvests',
            constraint=models.CheckConstraint(check=models.Q(('harvest_score__gte', 0), ('harvest_score__lte', 6)), name='A harvest score value is valid between 0 and 6'),
        ),
    ]
