# Generated by Django 3.0.3 on 2020-09-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='harvests',
            name='A harvest score value is valid between 0 and 6',
        ),
    ]
