# Generated by Django 3.0.3 on 2020-08-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0002_auto_20200830_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvests',
            options={'ordering': ('-harvest_date', 'shooter', 'shot_distance_yards'), 'verbose_name': 'Harvest', 'verbose_name_plural': 'Harvests'},
        ),
    ]
