# Generated by Django 3.0.7 on 2020-11-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0003_harvests_dnr_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvests',
            options={'ordering': ('-harvest_date', '-harvest_time', 'shooter', 'shot_distance_yards'), 'verbose_name': 'Harvest', 'verbose_name_plural': 'Harvests'},
        ),
    ]
