# Generated by Django 3.0.7 on 2021-02-23 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0004_auto_20201108_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_shot', models.ImageField(blank=True, null=True, upload_to='uploads/deer_shots/')),
                ('photo_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('-photo_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='harvests',
            name='removal_photos',
            field=models.ManyToManyField(blank=True, to='deer_harvest_logbook.HarvestPhoto'),
        ),
    ]
