# Generated by Django 3.0.7 on 2021-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0005_auto_20210222_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvests',
            name='cloud_level',
            field=models.CharField(choices=[('Clear Sky', 'Clear Sky'), ('Few Clouds', 'Few Clouds'), ('Scattered Clouds', 'Scattered Clouds'), ('Broken Clouds', 'Broken Clouds'), ('Shower/Rain', 'Shower/Rain'), ('Rain', 'Rain'), ('Thunderstorm', 'Thunderstorm'), ('Snow', 'Snow'), ('Mist', 'Mist'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='harvests',
            name='wind_dir',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='harvests',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
