# Generated by Django 3.0.7 on 2021-02-27 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0006_auto_20210226_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvests',
            name='estimated_temperature',
            field=models.IntegerField(default=-49, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(-50)]),
        ),
    ]
