# Generated by Django 3.0.7 on 2021-03-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0008_harvests_yards_ran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('elevation', models.DecimalField(decimal_places=0, default=764, max_digits=5, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=39.57523, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, default=-76.99604, max_digits=12, null=True)),
            ],
            options={
                'ordering': ('nickname', 'latitude', 'longitude'),
            },
        ),
        migrations.AddField(
            model_name='harvests',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='deer_harvest_logbook.Location'),
        ),
    ]
