# Generated by Django 3.0.7 on 2021-04-19 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deer_harvest_logbook', '0010_auto_20210326_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeerManagementPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(default='666999123', max_length=10)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('permit_id',),
            },
        ),
        migrations.AddField(
            model_name='harvests',
            name='crop_damage_permit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deer_harvest_logbook.DeerManagementPermit'),
        ),
    ]
