# Generated by Django 3.0.7 on 2021-04-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0011_auto_20210418_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvests',
            name='crop_damage_permit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deer_harvest_logbook.DeerManagementPermit'),
        ),
    ]
