# Generated by Django 3.0.7 on 2021-04-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0012_auto_20210418_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvests',
            old_name='crop_damage_permit_id',
            new_name='deer_management_permit_id',
        ),
        migrations.RemoveField(
            model_name='harvests',
            name='crop_damage_permit',
        ),
    ]
