# Generated by Django 3.0.7 on 2021-04-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deer_harvest_logbook', '0013_auto_20210418_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deermanagementpermit',
            name='permit_id',
            field=models.CharField(default='06375', max_length=10),
        ),
    ]
