# Generated by Django 3.0.7 on 2020-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=150)),
                ('page_hit_count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
