# Generated by Django 3.0.7 on 2020-10-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imrunicorn', '0002_auto_20201008_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHideList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pagecounter',
            options={'ordering': ('-page_hit_count', 'page_name')},
        ),
    ]
