# Generated by Django 3.0.3 on 2020-08-26 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invite_Date', models.DateField(default=datetime.date.today)),
                ('Show_Listing', models.BooleanField(default=False)),
                ('Desired_Time_Slot', models.CharField(choices=[('AM', '8:00am - 11:59am'), ('PM', '12:30pm - 4:30pm')], default='AM', max_length=2)),
                ('Cancel_Code', models.CharField(choices=[('InviteActive', 'Not Canceled'), ('GuestCanceledGood', 'Guest Canceled, good terms.'), ('GuestCanceledBad', 'Guest Canceled, bad terms.'), ('AdminCanceledGood', 'Admin Canceled, good terms.'), ('AdminCanceledBad', 'Admin Canceled, bad terms.')], default='InviteActive', max_length=22)),
                ('Invite_Secondary', models.BooleanField(blank=True, default=False, null=True)),
                ('MDShooters_Name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Real_Name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Phone_Number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('EMail', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Hours_Late', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('Event_Notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('Invite_Date', 'Invite_Secondary', 'MDShooters_Name', 'Phone_Number'),
            },
        ),
    ]
