# Generated by Django 3.0.7 on 2020-11-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelisting',
            name='Desired_Time_Slot',
            field=models.CharField(choices=[('AM', '8:00am - 11:59am'), ('PM', '12:30pm - 4:30pm'), ('D1', '8:00am - 5:00pm'), ('N1', 'NIGHT')], default='AM', max_length=2),
        ),
    ]
