# Generated by Django 3.0.7 on 2020-11-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0003_auto_20201122_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelisting',
            name='Desired_Time_Slot',
            field=models.CharField(choices=[('8:00am - 11:59am', '8:00am - 11:59am'), ('12:30pm - 4:30pm', '12:30pm - 4:30pm'), ('8:00am - 5:00pm', '8:00am - 5:00pm'), ('NIGHT', 'NIGHT')], default='8:00am - 11:59am', max_length=60),
        ),
    ]
