# Generated by Django 3.0.7 on 2020-11-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0004_auto_20201123_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelisting',
            name='Paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
