# Generated by Django 3.0.7 on 2021-01-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0008_packinglist_packinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packinglist',
            options={'ordering': ('-List_Date',)},
        ),
        migrations.AlterModelOptions(
            name='packinglistitem',
            options={'ordering': ('-Name',)},
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='Count',
        ),
    ]
