# Generated by Django 3.0.7 on 2021-01-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0009_auto_20210101_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packinglist',
            options={'ordering': ('List_Date',)},
        ),
        migrations.AlterModelOptions(
            name='packinglistitem',
            options={'ordering': ('Name',)},
        ),
    ]
