# Generated by Django 3.0.7 on 2021-01-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0010_auto_20210101_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packinglist',
            options={'ordering': ('-List_Date',)},
        ),
    ]
