# Generated by Django 3.0.7 on 2021-01-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminvite', '0011_auto_20210101_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistitem',
            name='Private_Item',
            field=models.BooleanField(default=False),
        ),
    ]
