# Generated by Django 3.0.7 on 2021-04-19 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_fostering', '0002_auto_20210419_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='MommaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momma_shot', models.ImageField(blank=True, null=True, upload_to='uploads/puppy_fostering/')),
                ('photo_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('-photo_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='momma',
            name='momma_photos',
            field=models.ManyToManyField(blank=True, to='puppy_fostering.MommaPhoto'),
        ),
    ]
