# Generated by Django 3.0.7 on 2021-04-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_fostering', '0003_auto_20210419_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puppy',
            old_name='cloud_level',
            new_name='sex',
        ),
    ]
