# Generated by Django 3.0.7 on 2021-05-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_fostering', '0004_auto_20210419_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='momma',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
