# Generated by Django 3.0.3 on 2020-08-25 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageBlurbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blurb', models.TextField(blank=True, null=True)),
                ('Is_Active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Main Page Blurbs',
                'ordering': ('-Is_Active', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PageBlurbOverrides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blurb', models.CharField(max_length=250)),
                ('Page_Link_From_Base', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Page Blurb Overrides',
                'ordering': ('Page_Link_From_Base', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WhatIsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Blurb', models.CharField(max_length=250)),
                ('Body', models.TextField()),
                ('Image_One', models.ImageField(blank=True, null=True, upload_to='uploads/announcements/what_is_new/')),
                ('Published', models.BooleanField(default=True)),
                ('Is_Sticky', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'What Is New',
                'verbose_name_plural': 'What Is New',
                'ordering': ('-Date', 'Blurb'),
            },
        ),
    ]
