# Generated by Django 3.0.2 on 2020-01-28 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Blurb', models.CharField(max_length=250)),
                ('Body', models.TextField()),
            ],
            options={
                'ordering': ('Date', 'Blurb'),
            },
        ),
    ]
