# Generated by Django 3.0.7 on 2020-12-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_whatisnew_image_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatisnew',
            options={'ordering': ('-Is_Sticky', '-Date', 'Blurb'), 'verbose_name': 'What Is New', 'verbose_name_plural': 'What Is New'},
        ),
    ]
