# Generated by Django 3.0.7 on 2021-03-02 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooting_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeevent',
            options={'ordering': ('-challenge_date', '-id')},
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='challenge_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
