# Generated by Django 3.0.7 on 2021-03-02 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooting_challenge', '0002_auto_20210301_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeevent',
            name='cloud_level',
            field=models.CharField(choices=[('Clear Sky', 'Clear Sky'), ('Few Clouds', 'Few Clouds'), ('Scattered Clouds', 'Scattered Clouds'), ('Broken Clouds', 'Broken Clouds'), ('Shower/Rain', 'Shower/Rain'), ('Rain', 'Rain'), ('Thunderstorm', 'Thunderstorm'), ('Snow', 'Snow'), ('Mist', 'Mist'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='estimated_temperature',
            field=models.IntegerField(default=-49, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(-50)]),
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='wind_dir',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
