# Generated by Django 3.0.3 on 2020-08-26 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loaddata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('elevation', models.DecimalField(decimal_places=0, default=764, max_digits=5, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=39.57523, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, default=-76.99604, max_digits=12, null=True)),
            ],
            options={
                'ordering': ('latitude', 'longitude', 'nickname'),
            },
        ),
        migrations.CreateModel(
            name='ShotCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('firearm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shot_collection_firearm', to='loaddata.Firearm')),
                ('load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shot_collection_hand_load', to='loaddata.HandLoad')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shot_collection_location', to='shooting_logbook.Location')),
                ('shooter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shooter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-collection_date', 'shooter'),
            },
        ),
        migrations.CreateModel(
            name='ShotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotNumber', models.IntegerField(null=True)),
                ('wind_speed', models.CharField(choices=[('NONE', 'no wind'), ('LIGHT', '0-3 MPH wind'), ('MODERATE', '4-7 MPH wind'), ('HEAVY', '8-12 MPH wind'), ('OTHER', '13+ MPH wind')], default='LIGHT', max_length=20)),
                ('wind_direction', models.CharField(choices=[('NO_VALUE_TOWARD', 'No Value (toward)'), ('NO_VALUE_BEHIND', 'No Value (behind)'), ('HALF_VALUE_TOWARD', '1/2 Value (toward)'), ('HALF_VALUE_BEHIND', '1/2 Value (behind)'), ('FULL_VALUE_ACROSS', 'Full Value (across)')], default='NO_VALUE_BEHIND', max_length=30)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shot_collection', to='shooting_logbook.ShotCollection')),
            ],
            options={
                'ordering': ('collection', '-shotNumber'),
            },
        ),
    ]
